version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: 0.0.0.0
    environment:
      - 0.0.0.0
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: unless-stopped
    networks:
      - backend
  app:
    build: ./app
    container_name: app
    restart: always
    ports:
      - 8081:8000
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge

